# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "bertvv/centos72"
		config.vm.provider "virtualbox" do |vb|
		config.vm.provision "shell", path: "all_prov.sh"
	end		
	config.vm.define "avm" do |avm|
		avm.vm.hostname = "avm"
		avm.vm.network "private_network", ip: "172.192.10.30"	
		avm.vm.network "forwarded_port", guest: 22, host: 2220, id: "ssh"	
		avm.vm.network "forwarded_port", guest: 80, host: 8000	
		avm.vm.provision "shell", path: "avm.sh"
	#127.0.0.1.:2222
	end
	
	config.vm.define "tomcat1" do |tomcat1|
		tomcat1.vm.hostname = "tomcat1"
		tomcat1.vm.network "private_network", ip: "172.192.10.31"	
		tomcat1.vm.network "forwarded_port", guest: 22, host: 2221, id: "ssh"	
		tomcat1.vm.network "forwarded_port", guest: 8080, host: 8001	
		tomcat1.vm.provision "shell", path: "prov1.sh"
	#127.0.0.1.:2200
	end
	
	config.vm.define "tomcat2" do |tomcat2|
		tomcat2.vm.hostname = "tomcat2"
		tomcat2.vm.network "private_network", ip: "172.192.10.32"
		tomcat2.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"	
		tomcat2.vm.network "forwarded_port", guest: 8080, host: 8002			
		tomcat2.vm.provision "shell", path: "prov2.sh"
	#127.0.0.1.:2201
	end
end